package com.openclassrooms.arista.data.database.entities

import androidx.room.Entity
import androidx.room.PrimaryKey
import androidx.room.ColumnInfo
import com.openclassrooms.arista.domain.model.ExerciseCategory


/**
 * Represents an exercise entry in the application's local database.
 *
 * This entity corresponds to the "exercise" table and encapsulates the details of a
 * performed physical activity, such as when it started, how long it lasted, its category,
 * and its intensity level.
 *
 * @property id The unique identifier for the exercise record (auto-generated by the database).
 * @property startTime The start time of the exercise, represented in milliseconds since the epoch.
 * @property duration The total duration of the exercise in minutes.
 * @property category The specific type of exercise performed (e.g., Running, Yoga), defined by [ExerciseCategory].
 * @property intensity An integer representing the vigor or difficulty of the exercise.
 */
@Entity(tableName = "exercise")
data class ExerciseEntity(
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    val id: Long = 0,

    @ColumnInfo(name = "start_time")
    val startTime: Long,

    @ColumnInfo(name = "duration")
    val duration: Int,

    @ColumnInfo(name = "category")
    val category: ExerciseCategory, //enum

    @ColumnInfo(name = "intensity")
    val intensity: Int
)