package com.openclassrooms.arista.data.database.entities

import androidx.room.Entity
import androidx.room.PrimaryKey
import androidx.room.ColumnInfo

/**
 * Represents an user entry in the application's local database.
 *
 * This class maps to the "user" table in the Room database. It is used to persist
 * user information such as their name and email address.
 *
 * @property idUser The unique identifier for the user. It is the primary key and serves as the database ID.
 *                  Defaults to 0 and is auto-generated by Room.
 * @property name The full name of the user.
 * @property email The email address of the user.
 */
@Entity(tableName = "user")
data class UserEntity(
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "idUser")
    val idUser: Long = 0,

    @ColumnInfo(name = "name")
    val name: String,

    @ColumnInfo(name = "email")
    val email: String

)
